/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskCompletion = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Int,
  'taskId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Nat,
  'name' : IDL.Text,
});
export const FrequencyType = IDL.Variant({
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'frequencyType' : FrequencyType,
  'name' : IDL.Text,
  'weeklyCount' : IDL.Nat,
});
export const AppSettings = IDL.Record({
  'redThreshold' : IDL.Nat,
  'weeklyBarWeeks' : IDL.Nat,
  'maxWeeklyFreq' : IDL.Nat,
  'dailyBarDays' : IDL.Nat,
  'daysPerWeek' : IDL.Nat,
  'amberThreshold' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTaskCompletion' : IDL.Func([IDL.Nat, IDL.Int], [TaskCompletion], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Nat], [Category], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Nat, FrequencyType, IDL.Nat],
      [Task],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTaskCompletionsInRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(TaskCompletion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppSettings' : IDL.Func([AppSettings], [], []),
  'updateCategory' : IDL.Func([Category], [Category], []),
  'updateTask' : IDL.Func([Task], [Task], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskCompletion = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Int,
    'taskId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Nat,
    'name' : IDL.Text,
  });
  const FrequencyType = IDL.Variant({
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'frequencyType' : FrequencyType,
    'name' : IDL.Text,
    'weeklyCount' : IDL.Nat,
  });
  const AppSettings = IDL.Record({
    'redThreshold' : IDL.Nat,
    'weeklyBarWeeks' : IDL.Nat,
    'maxWeeklyFreq' : IDL.Nat,
    'dailyBarDays' : IDL.Nat,
    'daysPerWeek' : IDL.Nat,
    'amberThreshold' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTaskCompletion' : IDL.Func([IDL.Nat, IDL.Int], [TaskCompletion], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Nat], [Category], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Nat, FrequencyType, IDL.Nat],
        [Task],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTaskCompletionsInRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(TaskCompletion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppSettings' : IDL.Func([AppSettings], [], []),
    'updateCategory' : IDL.Func([Category], [Category], []),
    'updateTask' : IDL.Func([Task], [Task], []),
  });
};

export const init = ({ IDL }) => { return []; };