/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'redThreshold' : bigint,
  'weeklyBarWeeks' : bigint,
  'maxWeeklyFreq' : bigint,
  'dailyBarDays' : bigint,
  'daysPerWeek' : bigint,
  'amberThreshold' : bigint,
}
export interface Category { 'id' : bigint, 'weight' : bigint, 'name' : string }
export type FrequencyType = { 'daily' : null } |
  { 'weekly' : null };
export interface Task {
  'id' : bigint,
  'categoryId' : bigint,
  'frequencyType' : FrequencyType,
  'name' : string,
  'weeklyCount' : bigint,
}
export interface TaskCompletion {
  'id' : bigint,
  'completedAt' : bigint,
  'taskId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTaskCompletion' : ActorMethod<[bigint, bigint], TaskCompletion>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, bigint], Category>,
  'createTask' : ActorMethod<[string, bigint, FrequencyType, bigint], Task>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTaskCompletion' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[bigint], [] | [Category]>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTaskCompletionsInRange' : ActorMethod<
    [bigint, bigint],
    Array<TaskCompletion>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppSettings' : ActorMethod<[AppSettings], undefined>,
  'updateCategory' : ActorMethod<[Category], Category>,
  'updateTask' : ActorMethod<[Task], Task>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];